package exceptionPracticies;

import java.util.InputMismatchException;
import java.util.Scanner;

public class MultipleCatchBlock {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		Scanner scan = new Scanner(System.in);
		try {
		
		System.out.println("enter a number");
		int num1 = scan.nextInt();

		System.out.println("enter another number");
		int num2 = scan.nextInt();
		
		int result = num1/num2;
		
		System.out.println("the division of 2 numbers is : " + result);
		}
		
		catch(ArithmeticException e)
		{
			System.out.println("plz do not enter 0 in denominatior");
		}
		
		catch(InputMismatchException e)
		{
			System.out.println("plz enter only Integer values");
		}
		

		catch(Exception e)
		{
			System.out.println("plz enter valid input");
		}
		scan.close();


	}

}
