package exceptionPracticies;

public class ExceptionDemo1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int i = 9;
		int j = 0;
		
		System.out.println(name.length());
		
		try {
		System.out.println("Result" + i/j);
		}
		catch(ArithmeticException e) {
			//e.printStackTrace();
			System.out.println(e.getMessage());
			System.out.println("please donot give 0as value of j");
		} 
		System.out.println("Result for addition " + i+j);
		System.out.println("Result for multiplication " + i*j);
		System.out.println("Result for substraction " + (i-j));

	}

}
